# Generated by Django 4.2.7 on 2023-11-05 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_alter_news_date_reported'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='images',
        ),
    ]
